# Latest documentation available at https://omines.github.io/datatables-bundle/#configuration
datatables:
    # Set options, as documented at https://datatables.net/reference/option/
    options:
        lengthMenu : [10, 25, 50, 100, 250, 500, 1000, 2500]
        pageLength: 50
        dom: "<'row justify-content-end'<'col-auto'f>><'row'<'col-sm-12 table-responsive'tr>><'row justify-content-between align-items-center'<'col-auto'i<'mt-1'l>><'col-auto'p>>"
        searching: true

    template_parameters:
        # Example classes to integrate nicely with Bootstrap 3.x
        className: 'table table-striped table-bordered table-hover data-table'

    # You can for example override this to "tables" to keep the translation domains separated nicely
    translation_domain: 'messages'
    method: 'GET'
    persist_state: 'fragment'
    language_from_cdn: true