twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        app_version: '%env(APP_VERSION)%'
        path_upload_image_user: '%upload.user%'
        path_upload_image_couverture: '%upload.couverture%'
        path_upload_image_articleCover: '%upload.articleContent%'
when@test:
    twig:
        strict_variables: true
